language: node_js

node_js: "5.5.0"

sudo: false

env:
  global:
    - GITHUB_REPO: github.com/$TRAVIS_REPO_SLUG
    - secure: "kyLbeW9FsgtpwtCjmgn5J21J8s4IoU+JHGakcVcU30yB2H9zIeJalM1z1UVBUTy8JO0F3oH/+eWNbKiEfqsM92APEK+lpwlxuJH717PTMM0X3ykG1I80Hq6dmCULl+FSaYOJ2WNMyCRSjqwzrfDNim0aGecAm7Ocj15omQXKBPhFstzu6tLOAft3FLPQfzV4thVW6y6fPRCMoCCDfpuNc+Dy7QgZ3K5uB7s69bx/iAuxgcZ2+6FfNJj0l6c5voTRJDHORGWmjTfAqFCCaYnkY881Zwc6IoxbynugON+6vbKi3T42o1lctqxL5Fo7aP50Ptpai/jqTu4uEVJuLGfnaLVysoV3wE4qoCl8LSJYxz51bqsOpZFG/24Y0xIBJ7HLUJ2X4/Ieau7gR2PhkVMiZTVliFkEzomaoIQ4MqWlkryT/O+LQQ9UB3oFoKDDAaIkuANLvlXsPUZfEku5EUxNUvTzq+y7dtCUl6F2vgsjdh0K7RpdzsiSSoijYotA6KkJyUsKsc5T5Ons684LZSI5Be5Z7LpjLnTHikR/ZXqPjxPhgcibOIoGLOa22TdOCpWO4Bm5aoYjMeU6X2ZIllmhplZsA88uIkELa7wyN6Xk2qY6v4Gfu86xGsQqmFyXVNtcPZ46CgODx5DxEoLr2WJ21SN+NqHZRvWat9RQk463Vc8=" # GITHUB_TOKEN

before_script:
  - travis_retry npm install codecov.io

script:
  - npm run test-single

after_success:
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
