language: node_js

node_js: "5.5.0"

sudo: false

env:
  global:
    - CF_DEPLOY_USER: fec_deployer
    - secure: "Z4yChO0zWjQG1pz3bM3/ECXXkPXkdt78Bl0yWonj7JEKPUSeFlp1bg8adl+7Mu1vZMEiqoL/7SjzRSI6ZD1xF4yBbIBUV0JEFeL8/mFSA/AGkr7eI72Acv4Pe4eFqFnHxC3dHEoxMR+w06SidLOtg+fBkRi+74xHH/VxXpLbHN5F4n8R+QDnYQq06NCltz4wtue5ZmrmxuQZN6HMFwTAuEYgOHyHx99M5dsmFepqgPa/Pp2MrgEDnUAZaSo9mED7oLMgmE+Upt+Ow1FlhchJAh33YpxgA0Uwl/B4ZF902vLcd9Cl4ajS3b9bPZIzn6SKx5QK17eQaVVLLPcuBKfsu9xoJjJKUZfxFSo2tsgMGs9O2Dv9TLoueX/TPp3DWnj4wq7welS5anJqOWrS9WYImADrzPGDMhJFtwwOVBnu7Q+Gw3pWuI7WeYZ7R9S7rk6uQkUxcCLYM6SOeHhenvTsQNfMvos5Ke4ioUsOPcR7jocIhbNiWkBwrOX5ZYDuKon2JHWSdvO9ehQqIEh61ir5iug7du3huPRVPqOen0Hsr4uG3AZxXg16qGy4QMy1mHN29d3J28p/qELi8nhhMndiwdw6bLBGQhs0jJ533zgDb42xZJTj+0yTFiwm8B9h0+h3wiiuXPxUfMQ/zV729oxP4Gs0DqviwK/OcmR/H2cQpvY=" # CF_DEPLOY_PASSWORD

before_script:
  - travis_retry npm install codecov.io

script:
  - npm run build-js
  - npm run build-sass
  - npm run test-single

after_success:
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

before_deploy:
  - npm run build
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  - provider: script
    script: ./bin/cf_deploy.sh fec-style fec dev
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email:
      secure: "KtSDH6Qlnm1it8CZnX4W7fXu3lSe5UrqskyLkaAeDzBarHxki2bLflXa+D0G2xC1WOeu9rFXjfXLVpdpa46CHvVrJ15Y4kOr3xHnf823L+MYsFtb3VQBtoEA/vs+xP0LPlU9IoOO2ZjaLgDCPAVi54kR8KuXrDfzb0Ync/aYY8MIfSvSm9GLqt+VQUTo4oQdVm1G9NzKz025K/DYi8mWKvMF7lhYxBeBGRH/pnemUMCIEYTwQGZ6io/fccXv9N9g1EOu6uouU/xibth7HxQS9VLvlQigMyQ8gy9UI/x0O/hoBDA6jEEfQ8zQAczK11rRlCVedcD5a9NqHwUv/yplhYuS/AFtu4uqDK3aSYC2Udi6b9eMH1nlIt/mdl99JYhWM+YLaROvRviSf73FB4jpNIbXILQai7Q0K+N53uZwsxHaq0oJ7ADsts75tK4br8jbZtMxcKO+Xg+rY/nQ/X/EkK4qEk+1/8TwrTypk/YQd+M4Hk463+kdEsBs7u1P4uLHekuagcODVCNJsL+qIx321+gE2HiDVD3kf3aNcST4Q8sZGMFOiPBvtTVjh0nKYADGDmtHnAzqK09iwmDCtOcL2/vWK4+/nrlPAsa9sVw2gGiRocWTsmrfJ8rq3M/FxfJAlQKWQ2QKjYfNSKHqPWAxniIXkFWptXyi/CJKdRCNfeQ="
    api_key:
      secure: "dkzgI5VgMbrQa4w9uVH+TDGtwdRGFgZSWOByS7MFxvyuKzKF2ckufk9KCXb9mTFl3y46b2etDq9M+JHSOsONBmz9nHHNmLsMJbstiN9AvwhCXmbsowU7T8TYyeBN5fjU3jmPq2u2VhfsSuDi4O1QKyJc6j8pMWro/8bKkxneDGyQm/QGwcIYewp4khLJdPQ+QUyaOMG6JfHwzmxJyDzN1J0dt5phjdB0JDyJOCEISUM0krUGH/GfyXE13XLYzxU2E7oIgHrrRARJVtqCyTZIvIW1o+mZQoY+HEf4AIRfgzHS+HJnbPPxwIH4AHwnEGC1cyvxWztY9up29VL4Ne9Nt8ZCmvKNP3AabuQD/2HE117SRcLrQXPZLbD0HOg9TLT89iFfLfmh8HgXJb9dJFuh2CuFyiAplTlmsRk1vp1GhZuqpktacq3+YmBlO7L2gRdPNtFXVyIEROl3K9tDWVMqwJSTJMqRnPBvYH9IZwISKWBwYMLdmCYFuFjkrjrpq3pRxF4ISUK97sEVlWgXlz4kBPQNXE5/yIuMCvXyPl3dUYgmUsGvu5e20JOqGV61ILr2H9BQ75t9tBJJfh6yNEhd3QLf/umxOFJdXsES00Tgm72kBS+qITuHSw+hxP6n7wqohfBT0O/p6l3bzj87PDz/aCfYtByPj+veX8Y5kXnCYnU=" # 18f-devops
    on:
      branch: master
      tags: true
