language: node_js

node_js: "5.5.0"

sudo: false

env:
  global:
    - GITHUB_REPO: github.com/$TRAVIS_REPO_SLUG
    - secure: "zB7tPSfXQsANPzOXQN6GMElBsCMPyIpVbjcSHk63ygzEwmxXf3jzo6VVHtQbzZUPOm30SQa7ettDPTrlaElkb0iD5Icrd02A2kGpTtHJ1giJPGLTXupNA8H7cCJBEN1Ko+/CS/q0NtMNY6NKuGZST/6pLuZtY919DuhdwcBiw37nCxOPdwkzFaRKQB0d01MSdMgFWvDP/dvUm4Ccej1vxMbtRq56fq4BzYkQyvFL2RGm0KJ2dPCd/w0SIFyYsI4skzULO52VaPvRxn9R+dmD+c8qUkJOCROMV4lvnPUkGGowESUQQ4Ox4ER32Ywd5Qy1ZhZ+NtG8QOBeC5V0cPW2UdeEkJF+2nG8Z5uVFq0EUTGLx/qG+ZfxhNi1MNHhXGV5mny8j8FkFPqJxikPEZ09jUPrsBq43JlM5XVnoyncejFpBgdu8soL5UuKNwDX5TJ6WnM1XIrQ+RCffErrntJgu9GMJKgIAODccKWRyJUGDmGFeFOSlYLBA5sQ19VjRJ5z9EPzvSVAm+CS7RvGRV1t6p0OT5W16/ixCI+9MmtIRsjYLxUgC62acZBkPpSQ7ca4U86bz6g8h+bUgY8q1/846GAsiMakHmKwYKCOA53Hn7ROP/P2b2sENf9p8XgIDQTkxfd2lnVGU07iEIW0SUvoFHaJvkyXmv52Om1pHK3PqcY=" # GITHUB_TOKEN

before_script:
  - travis_retry npm install codecov.io

script:
  - npm run build-js
  - npm run build-sass
  - npm run test-single

after_success:
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email:
      secure: "koO78XV++b9pRYXV7QQ6YuA2xPzr+s0y6IxwsCMdB0hHx4r8PQ7iMu+e5cyTPL1AX77U0yGoqoe5+3ZhLffkLM4pL/aIDUhUt+xXyE8f6FIH6FeTiZ9Z9Wwzrfo9//GsJ5XuXNP5pIP9vhCmkfbRrInZRpE+py/FmadGmbJJSxhMEUZNGfCdxY+pdmGLqDF2OfHMy34h07rlV6zOPchy1ITES9j9Vy/yGl80goIn7FwlJKbnczD99sSeo8Egebm4pj233rJz1RqK2FDgj0+fGywYyXzKrWp7YzffZ9mrCf7/wX3H6KzB8PbgGjv31HsiHj1D0oGv9yTTk0/lQxep2gbaF2PjYWliHaSsTeCI/iBzitqfwfJxEL4wso/7E0hsasLaktd/DmGVg6A7R6SQ35+3RJQ2p0lm0gP5lwTuYZKRxj8QvXVsgzfCKnBT9TpjqHCtyjidwJ1kYlWJEU3QteZUXCNO909ofKRPNknm4Sm6Vi5S9Sd01z41CMFPERbTxFJ43++qq7O0i6BEj0xaz4lTeDK12ZoaKcrCkjW0mfFPhM7fPFdS4DopmjOgygN5tWZh0taDbrZGDOlYieIefRXzQbkWEb/WsJB5jj3XE8Ca0NdcQ8PLsCdLSYzDt1qImftVuR2Lzh4BHJNquOcZMgnvEVFvy4zQ7kdYcHOEOKo="
    api_key:
      secure: "X81F3fbgMkFh982vWYxAjbh6lkabjzs8Ge2trai1TN/Vn49DFA3EjUvxPKqj3e2hzn8MK+AEFYjW3+sw3DoSzUNhgFnKvpi8FYY67XKLSX57jAM6mYTb2VjW2rpHjTr0sj2t4KsV3ij6//roxu9nYg/HAcjKW7/4g/E2nAgQxtBRMs6kF82JRFcyIMWN1IyMDiSS428f3oPBWIlKSNphMdxW6rWhbi3rX5bx6CfkoKbeBWFKhMfggzB+I/HsqEohee6DxsxvJM0ue4Q0CFlrgoczV3NCLBnsBReRNi9E7T93lYLw4x5iLij9a/4Qw5e4jl4J58fQE1NBAAKWeEkLDnMsWxrO+KjRNc0qas67yTEzwOhUYk1bhMh7LXsJWUXUf5xiRSSFor4JwCwGRdrkLczFGbeYKM/1DlUoPy0qp9vRsH+xCvu0igv7h0qC+KlzcH4ur9ZfRc/qpZgZt1EeRiXX91LfY+161abakdzWkx70eCEPt9V2O3zORdY2UctgK3Dv1rfkvACMqngqrsnxW6CHfZdQ/wpoPLhcusabhMCJaLj6MPGLcABt7/Sz8VIuowY4JP5rWzr+JIoLMdv/+teykiqe68adxF8owFrbX8Gc/7NNGzX1vy/kXC2SVDT/uMatq0jD4DzTYt+LHrs3btDemdZmVkwaOh8WW2sUXzw="
    on:
      branch: master
      tags: true
